# Generated by Django 2.1.7 on 2019-05-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Book')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.History')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='what',
            unique_together={('isbn', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('isbn', 'cid')},
        ),
    ]
