# Generated by Django 2.1.7 on 2019-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='birthyear',
            field=models.IntegerField(default=1990),
        ),
    ]
