# Generated by Django 2.1.7 on 2019-05-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190505_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthyear',
            field=models.IntegerField(default=1990, max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='what',
            unique_together=set(),
        ),
    ]
