# Generated by Django 2.1.7 on 2019-12-09 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190622_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('selltype', models.CharField(choices=[('F', 'Flea'), ('A', 'Auction')], default='F', max_length=1)),
                ('statustype', models.CharField(choices=[('S', 'Sold'), ('E', 'Expired'), ('R', 'Running')], default='E', max_length=1)),
                ('expire', models.DateTimeField(default=0)),
                ('highest_price', models.IntegerField(default=0)),
                ('basic_price', models.IntegerField(default=0)),
                ('current_price', models.IntegerField(default=0)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('explanation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rating', models.IntegerField(default=0)),
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthyear',
            field=models.PositiveIntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='home.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='home.User'),
        ),
    ]
