# Generated by Django 2.1.7 on 2019-12-11 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191209_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(choices=[(datetime.datetime(2019, 12, 14, 12, 39, 45, 570014), '3 Days'), (datetime.datetime(2019, 12, 18, 12, 39, 45, 570014), '7 days'), (datetime.datetime(2020, 1, 10, 12, 39, 45, 570014), '30 days')], default=datetime.datetime(2019, 12, 12, 12, 39, 45, 570014)),
        ),
    ]
