# Generated by Django 2.1.7 on 2019-12-12 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191211_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(choices=[(datetime.datetime(2019, 12, 15, 16, 58, 24, 651346), '3 Days'), (datetime.datetime(2019, 12, 19, 16, 58, 24, 651346), '7 days'), (datetime.datetime(2020, 1, 11, 16, 58, 24, 651346), '30 days')], default=datetime.datetime(2019, 12, 13, 16, 58, 24, 651346)),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
