# Generated by Django 2.1.7 on 2019-12-12 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191212_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(choices=[(datetime.datetime(2019, 12, 16, 2, 48, 59, 780037), '3 Days'), (datetime.datetime(2019, 12, 20, 2, 48, 59, 780037), '7 days'), (datetime.datetime(2020, 1, 12, 2, 48, 59, 780037), '30 days')], default=datetime.datetime(2019, 12, 16, 2, 48, 59, 780037)),
        ),
    ]
