# Generated by Django 2.1.7 on 2019-12-12 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191213_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 17, 53, 57, 227999, tzinfo=utc)),
        ),
    ]
