# Generated by Django 2.1.7 on 2019-12-12 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191213_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expirechoice',
            field=models.CharField(choices=[('3', '3 Days'), ('7', '7 days'), ('0', '30 days')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 17, 59, 15, 665718, tzinfo=utc)),
        ),
    ]
