# Generated by Django 3.0 on 2019-12-12 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191213_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 19, 12, 3, 552610, tzinfo=utc)),
        ),
    ]
